# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven and Docker publish

on: 
  push:
    branches:
    - main
    - 'ci/**'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    maven:    
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          cache: 'maven'
      - name: Check Java version
        run: java -version
      - name: Build with Maven
        run: mvn clean package verify
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}    
      - name: Upload artifact for Docker job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  docker:
    runs-on: ubuntu-latest
    needs: maven
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Download artifact from Maven job
      uses: actions/download-artifact@v3
      with:
        name: java-app
    - name: Log in to Docker
      run: docker login ghcr.io -u snorav3 -p ${{ github.token }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/snorav3/cubix/1/optional/app:springboot
    - name: Publish the Docker image
      run: docker push ghcr.io/snorav3/cubix/1/optional/app:springboot
      